title: IGDCB
url: ""
baseurl: "/igdcb"
description: ""

logo_en: "svg/logo.en.full-color.nobg.200x72.min.svg"
logo_he: "svg/logo.he.full-color.nobg.200x61.min.svg"

excerpt_separator: <!--excerpt-end-->

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "" 
      type: "posts"
    values:
      layout: "post"
      language: "he"
  - scope:
      path: "*/en/*" 
      type: "posts"
    values:
      language: "en"
